name: setup-go
description: Setup Go environment

runs:
  using: composite
  steps:
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./app/go.mod
          cache: false
      - uses: actions/cache@v4
        id: go-cache
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/go/bin
          key: go-${{ hashFiles('app/go.sum') }}-${{ hashFiles('app/**/*.go') }}
      - name: Install Dependencies 
        if: steps.go-cache.outputs.cache-hit != 'true'
        shell: bash
        working-directory: ./app
        run: go get -v -t -d ./...