name: go-app
on:
  pull_request:
    paths:
      - "app/**"
      - ".github/actions/**"
      - ".github/workflows/main.yaml"

jobs:
  small-api-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - name: run small tests
        working-directory: ./app
        run: ${{ env.GOTESTSUM_BIN }}/gotestsum --format github-actions --junitfile api-test-log.xml ./...