name: go-app
on:
  pull_request:
    paths:
      - "app/**"
      - ".github/actions/**"
      - ".github/workflows/main.yaml"

jobs:
  api-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
        with:
          go-mod-path: app/go.mod
      - uses: golangci/golangci-lint-action@v6
        with:
          working-directory: app
          args: --timeout=30m
          skip-save-cache: true
  small-api-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
        with:
          go-mod-path: app/go.mod
      - name: run small tests
        working-directory: ./app
        run: go run gotest.tools/gotestsum@latest --format github-actions --junitfile api-test-log.xml ./...